name: programming run
on:
    workflow_dispatch:
      inputs:
        model_uri:
          description: "Registered Model name"
          required: true
        model_version:
          description: "model version"
          required: true
env:
  MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
  MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
  MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}



jobs:
  artifact_downloader:
      runs-on: ubuntu-latest
      steps:
          - name: checkout repository
            uses: actions/checkout@v2
          
          - name: set up python
            uses: actions/setup-python@v5
            with:
              python-version: '3.11'

          - name: create environment
            run: |
              pip install --upgrade pip
              python -m venv myenv
              source myenv/bin/activate

          - name: install dependencies
            run: |
              pip install -r requirements.txt

          - name: Run the script and generate artifact
            run: |
              python artifact_download.py --model_uri=$model_uri --model_version=$model_version --MLFLOW_TRACKING_URI=$MLFLOW_TRACKING_URI --MLFLOW_TRACKING_USERNAME=$MLFLOW_TRACKING_USERNAME --MLFLOW_TRACKING_PASSWORD=$MLFLOW_TRACKING_PASSWORD
            env:
              model_uri: ${{ github.event.inputs.model_uri }}
              model_version: ${{ github.event.inputs.model_version }}
              MLFLOW_TRACKING_URI: $MLFLOW_TRACKING_URI
              MLFLOW_TRACKING_USERNAME: $MLFLOW_TRACKING_USERNAME
              MLFLOW_TRACKING_PASSWORD: $MLFLOW_TRACKING_PASSWORD

              
              
  dockerbuildandpush:
      runs-on: ubuntu-latest
      needs: artifact_downloader
      
      steps:
          - name: checkout repository
            uses: actions/checkout@v2

          - name: setup docker builtx
            uses: docker/setup-buildx-action@v1
        
          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUBUSER }}
              password: ${{ secrets.DOCKERPASS }}

          - name: Build and push Docker image
            uses: docker/build-push-action@v5
            with:
              context: .
              platforms: linux/amd64
              push: true
              tags: nileshdalagade/mlflow_deeplearning:latest
              build-args: |
                model_uri = ${{ github.event.inputs.model_uri }}
                model_version = ${{ github.event.inputs.model_version }}
                MLFLOW_TRACKING_URI = ${MLFLOW_TRACKING_URI}
                MLFLOW_TRACKING_USERNAME = ${MLFLOW_TRACKING_USERNAME}
                MLFLOW_TRACKING_PASSWORD = ${MLFLOW_TRACKING_PASSWORD}