name: programming run
on:
    workflow_dispatch:
      inputs:
        model_uri:
          description: "Registered Model name"
          required: true
        model_version:
          description: "model version"
          required: true
 
env:
  MLFLOW_TRACKING_URI: ${{secrets.MLFLOW_TRACKING_URI}}
  MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
  MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}


jobs:
  dockerbuildandpush:
      runs-on: ubuntu-latest
      steps:
          - name: checkout repository
            uses: actions/checkout@v2

          - name: setup docker builtx
            uses: docker/setup-buildx-action@v1
        
          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUBUSER }}
              password: ${{ secrets.DOCKERPASS }}

          - name: Build and push Docker image
            uses: docker/build-push-action@v5
            with:
              context: .
              platforms: linux/amd64
              push: true
              tags: nileshdalagade/mlflow_deeplearning:latest
              build-args: |
                model_uri=${{ github.event.inputs.model_uri }}
                model_version=${{ github.event.inputs.model_version }}
                MLFLOW_TRACKING_URI= $MLFLOW_TRACKING_URI
                MLFLOW_TRACKING_USERNAME=$MLFLOW_TRACKING_USERNAME
                MLFLOW_TRACKING_PASSWORD=$MLFLOW_TRACKING_PASSWORD